version: "3"
services:
  server:
    image: node:latest
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - PGUSER=polina
      - PGHOST=db
      - PGPASSWORD=composerpass
      - PGDATABASE=composers
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=composers
      - POSTGRES_USER=polina
      - POSTGRES_PASSWORD=composerpass

volumes:
  dbdata:
